import type { MindMapTheme, MindMapThemeId } from "./types";

export const themes: Record<MindMapThemeId, MindMapTheme> = {
  classicLight: {
    id: "classicLight",
    name: "经典浅色",
    canvasBackground: "#ffffff",
    linkStroke: "#cbd5e1",
    nodeFill: "#ffffff",
    nodeStroke: "#94a3b8",
    nodeText: "#0f172a",
    rootFill: "#0f172a",
    rootStroke: "#0f172a",
    rootText: "#ffffff",
    selectedFill: "#dbeafe",
    selectedStroke: "#2563eb",
    hoverStroke: "#0f172a",
    toggleFill: "#ffffff",
    toggleStroke: "#94a3b8",
    toggleText: "#0f172a",
    accent: "#2563eb",
  },
  classicDark: {
    id: "classicDark",
    name: "经典深色",
    canvasBackground: "#0b1220",
    linkStroke: "#334155",
    nodeFill: "#0f172a",
    nodeStroke: "#475569",
    nodeText: "#e2e8f0",
    rootFill: "#e2e8f0",
    rootStroke: "#e2e8f0",
    rootText: "#0b1220",
    selectedFill: "#1e293b",
    selectedStroke: "#60a5fa",
    hoverStroke: "#e2e8f0",
    toggleFill: "#0f172a",
    toggleStroke: "#475569",
    toggleText: "#e2e8f0",
    accent: "#60a5fa",
  },
  ocean: {
    id: "ocean",
    name: "海洋",
    canvasBackground: "#f0f9ff",
    linkStroke: "#7dd3fc",
    nodeFill: "#ffffff",
    nodeStroke: "#38bdf8",
    nodeText: "#0c4a6e",
    rootFill: "#0284c7",
    rootStroke: "#0284c7",
    rootText: "#ffffff",
    selectedFill: "#e0f2fe",
    selectedStroke: "#0284c7",
    hoverStroke: "#0369a1",
    toggleFill: "#ffffff",
    toggleStroke: "#38bdf8",
    toggleText: "#0c4a6e",
    accent: "#0284c7",
  },
  forest: {
    id: "forest",
    name: "森林",
    canvasBackground: "#f0fdf4",
    linkStroke: "#86efac",
    nodeFill: "#ffffff",
    nodeStroke: "#22c55e",
    nodeText: "#14532d",
    rootFill: "#16a34a",
    rootStroke: "#16a34a",
    rootText: "#ffffff",
    selectedFill: "#dcfce7",
    selectedStroke: "#16a34a",
    hoverStroke: "#14532d",
    toggleFill: "#ffffff",
    toggleStroke: "#22c55e",
    toggleText: "#14532d",
    accent: "#16a34a",
  },
  sunset: {
    id: "sunset",
    name: "日落",
    canvasBackground: "#fff7ed",
    linkStroke: "#fdba74",
    nodeFill: "#ffffff",
    nodeStroke: "#fb923c",
    nodeText: "#7c2d12",
    rootFill: "#ea580c",
    rootStroke: "#ea580c",
    rootText: "#ffffff",
    selectedFill: "#ffedd5",
    selectedStroke: "#ea580c",
    hoverStroke: "#7c2d12",
    toggleFill: "#ffffff",
    toggleStroke: "#fb923c",
    toggleText: "#7c2d12",
    accent: "#ea580c",
  },
  mono: {
    id: "mono",
    name: "极简黑白",
    canvasBackground: "#ffffff",
    linkStroke: "#1f2937",
    nodeFill: "#ffffff",
    nodeStroke: "#111827",
    nodeText: "#111827",
    rootFill: "#111827",
    rootStroke: "#111827",
    rootText: "#ffffff",
    selectedFill: "#f3f4f6",
    selectedStroke: "#111827",
    hoverStroke: "#111827",
    toggleFill: "#ffffff",
    toggleStroke: "#111827",
    toggleText: "#111827",
    accent: "#111827",
  },
};

export const getTheme = (themeId: MindMapThemeId | null | undefined): MindMapTheme => {
  if (themeId && themes[themeId]) return themes[themeId];
  return themes.classicLight;
};

